# Generated by Django 5.2.3 on 2025-06-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id_protocolo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='chamados/anexos/', verbose_name='Anexo')),
                ('categoria', models.CharField(choices=[('software', 'Software'), ('rede', 'Rede'), ('hardware', 'Hardware'), ('comunicacao', 'Comunicação'), ('configuracoes', 'Configurações'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='baixa', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('aberto', 'Aberto/Disponível'), ('fechado', 'Fechado'), ('concluido', 'Concluído'), ('reaberto', 'Reaberto')], default='aberto', max_length=10, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('data_reabertura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Reabertura')),
                ('solucao', models.TextField(blank=True, null=True, verbose_name='Solução')),
                ('anexo_solucao', models.FileField(blank=True, null=True, upload_to='chamados/solucoes/', verbose_name='Anexo da Solução')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'db_table': 'chamado',
            },
        ),
    ]
