# Generated by Django 5.2.3 on 2025-06-25 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='chamados_criados', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='tecnico',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_assumidos', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável'),
        ),
    ]
