# Generated by Django 5.2.3 on 2025-06-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='data_reabertura',
        ),
        migrations.AddField(
            model_name='chamado',
            name='anexo_cliente',
            field=models.FileField(blank=True, null=True, upload_to='chamados/anexos_cliente/', verbose_name='Anexo do Cliente'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='anexo_tecnico',
            field=models.FileField(blank=True, null=True, upload_to='chamados/anexos_tecnico/', verbose_name='Anexo do Técnico'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto/Disponível'), ('em_atendimento', 'Em Atendimento'), ('fechado', 'Fechado')], default='aberto', max_length=20, verbose_name='Status'),
        ),
    ]
