# Generated by Django 5.2.3 on 2025-06-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_remove_chamado_data_reabertura_chamado_anexo_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='anexo_cliente',
            field=models.FileField(blank=True, null=True, upload_to='anexos/'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='anexo_solucao',
            field=models.FileField(blank=True, null=True, upload_to='anexos/'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='anexo_tecnico',
            field=models.FileField(blank=True, null=True, upload_to='anexos/'),
        ),
    ]
