# Generated by Django 5.2.3 on 2025-06-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Matrícula'),
        ),
    ]
